### ISSUE TITLE
how to resume I/O truncated message decoding?

### ISSUE THREAD

**Issue by glycerine** [tinylib/msgp#109]
2e776fce9d47cb00819f6dc939a708dbb3085cb6

Am I using DecodeMsg() wrong or is this a bug?  It is highly likely I may not be using DecodeMsg() properly; how should one recover from failed attempt to read a truncated message?

I'm trying to recover after a torn read, but I'm getting `msgp: attempted to decode type "int" with method for "bin"`. The test below fails when truncated after the 2nd byte.

~~~
package main

import (
	"bytes"
	"fmt"

	"github.com/tinylib/msgp/msgp"
)

//go:generate msgp

type ByteSlice []byte

func panicOn(err error) {
	if err != nil {
		panic(err)
	}
}

func chkb(a, b []byte) {
	if len(a) != len(b) {
		panic("chkb: len differ")
	}
	for i := range a {
		if a[i] != b[i] {
			panic("chkb: bytes differ")
		}
	}
}

var p = fmt.Printf

func main() {
	// This is a test of torn messages: truncated due to I/O pause, and then later resumed.
	//
	// Here we do a simple msgpack encoding of a 3 byte payload in []byte, called a ByteSlice
	// to get the msgp generated methods.
	//
	// The following is a test of decoding bin8 when the outmost []byte message
	// has been truncated.
	//
	// Given that we may read a ByteSlice ([]byte) msgpack message
	// that can be torn (io stall) at any byte boundary, when try to
	// decode any number of bytes of a message that is torn, we should get
	// an error, even if this happens multiple times.
	//
	// More: When the full bytes do become available we should be able to
	// pick up and read the whole message sucessfully; we should proceed where we left off.

	payload := ByteSlice([]byte{0x1, 0x2, 0x3})
	msgpacked, err := payload.MarshalMsg(nil)
	panicOn(err)

	n := len(msgpacked)
	p("\n len of msgpacked,  n = %d.  message = '%#v' should be bin8/0xc4\n", n, msgpacked)
	//len of msgpacked,  n = 5.  message = '[]byte{0xc4, 0x3, 0x1, 0x2, 0x3}' should be bin8/0xc4

	buf := bytes.NewBuffer(msgpacked)
	mpr := msgp.NewReader(buf)

	var payload2 ByteSlice
	err = payload2.DecodeMsg(mpr)
	panicOn(err)

	chkb([]byte(payload), []byte(payload2))
	p("\nuntorn payload message comes back fine.\n")

	// now try tearing payload and recovering at any point 0..n-1

	m := n - 1
	// at any tear point we should be able to recover
	for i := 0; i < m; i++ {
		var payload3 ByteSlice

		// bbuf simulates a file or network that may interrupt (pause)
		// the data stream at any point, so that it appears truncated
		// for the moment.
		bbuf := bytes.NewBuffer(msgpacked[:i])
		mpr := msgp.NewReader(bbuf)
		err = payload3.DecodeMsg(mpr)

		// torn, so we should get error!
		if err == nil {
			panic(fmt.Sprintf("should have gotten error! failed to notice tear at %d\n", i))
		}

		// we should be able to resume after getting the rest of the bytes
		_, err = bbuf.Write(msgpacked[i:])
		panicOn(err)

		err = payload3.DecodeMsg(mpr)
		panicOn(err)

		chkb([]byte(payload), []byte(payload3))
		p("successful test for tearing at %d out of %d bytes\n", i, n)
	}
}

/*
output:

 len of msgpacked,  n = 5.  message = '[]byte{0xc4, 0x3, 0x1, 0x2, 0x3}' should be bin8/0xc4

untorn payload message comes back fine.
successful test for tearing at 0 out of 5 bytes
successful test for tearing at 1 out of 5 bytes
panic: msgp: attempted to decode type "int" with method for "bin"

goroutine 1 [running]:
main.panicOn(0x882041f2b0, 0x820274580)
    /Users/jason/tmp/f.go:16 +0x4b
main.main()
    /Users/jason/tmp/f.go:93 +0x7cb
jason@jasonsmac ~/tmp $

*/
~~~

**Comment by glycerine** [comment]
Ah. It does appear that

https://github.com/tinylib/msgp/blob/master/msgp/read.go#L736

does a Skip() before knowing that it has a full read available. So this looks like a bug, because there's no way to rewind the stream and try again after you've called Skip(), and the state of the parse is thus lost.

**Comment by ebfe** [comment]
I think the problem is that you are using bytes.Buffer and that returns io.EOF
when the internal buffer is drained. That causes DecodeMsg to return with an
error and parsing state is lost (as far as I know there is no way to
resume/recover a failed call to DecodeMsg).

Here is an example using pipes that doesn't have that problem:
```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/tinylib/msgp/msgp"
)

//go:generate msgp
type ByteSlice []byte

func main() {
	msg := []byte{0xc4, 0x3, 0x1, 0x2, 0x3}

	r, w, err := os.Pipe()
	if err != nil {
		panic(err)
	}

	go func() {
		for i, b := range msg {
			fmt.Println("writing byte", i)
			w.Write([]byte{b})
			time.Sleep(1 * time.Second)
		}
	}()
	var payload ByteSlice

	mr := msgp.NewReader(r)
	payload.DecodeMsg(mr)
	fmt.Println("%+v\n", payload)
}
```

**Comment by glycerine** [comment]
Okay. Since I need to be able to decode from sources (like internal buffers or dropped and resumed network connections) where EOF can happen at any point, and I don't have a graceful way to recover, I still think of this as a bug.

**Comment by glycerine** [comment]
Here's a minimal workaround (PR #110) for this issue. If I can Peek() ahead on the stream and decode the bin8/bin16/bin32 myself, then I can avoid advancing the reader and getting into an unrecoverable situation.  Not as nice as having the library handle EOF transactionally, but suffices for my use for now. And it is generally useful to be able to access the fwd Reader.

**Comment by philhofer** [comment]
In the general case, it's tough to ensure that objects are read atomically without unbounded (or at least *very large*) resource use.

For a while I've considered adding an API that would allow users to parse `bin`/`str` objects incrementally, much like the existing `map`/`array` API. In other words, you would have something along the lines of 
```go
func (w *Writer) WriteBinHeader(sz uint32) error
func (r *Reader) ReadBinHeader() (uint32, error)
func (w *Writer) WriteStrHeader(sz uint32) error
func (r *Reader) ReadStrHeader() (uint32, error)
```
That way, you could handle the reads and writes yourself, which would let you do the sort of EOF recovery you suggest.

**Comment by glycerine** [comment]
@philhofer Nice. For what its worth my workaround does what I imagine your ReadBinHeader does, but returns all three numbers that you need to fully deal with the Bin message. It looks like this.  I would still need #110 as well for the Peek() ahead to populate p.

~~~
func DecodeBinHeader(p []byte) (ntotal int, ninside int, nheader int, err error) {

    if len(p) == 0 {
        err = NotEnoughBytes
        return
    }
    switch p[0] {
    case bin8:
        if len(p) < 2 {
            err = NotEnoughBytes
            return
        }
        ninside = int(p[1])
        nheader = 2
        ntotal = ninside + nheader
       return 
    case bin16:
...

~~~

**Comment by philhofer** [comment]
Reads of small values (everything except `bin`, `str`, and `extension`s) are already "transactional;" we could make reading the headers have the same kind of guarantee. Then you can write your own bookkeeping around handling errors from `(*Reader).Read()`.

**Comment by glycerine** [comment]
@philhofer are maps transactional small values as well?

**Comment by philhofer** [comment]
Yep. The semantics of `(*fwd.Reader).Next()` are that it only advances the reader state if it successfully produces the next 'n' bytes.

Methods for reading `str`/`bin`/`ext` are the only ones that don't promise to preserve the state of the decoder if they fail, because they read a data segment that is (potentially) larger than the size of the buffer. Everything else makes it trivial to determine whether or not the call will be successful without mutating the reader's state.

**Comment by philhofer** [comment]
@glycerine take a look at #111 and let me know what you think.

**Comment by oliverjanik** [comment]
I believe I see the same problem when Decoding r.Body directly from http handleFunc.

```go
func handleHashes(w http.ResponseWriter, r *http.Request) {
	log.Println("Header", r.Header)

	var hashes sync.BlockHashes
	if err := msgp.Decode(r.Body, &hashes); err != nil {
		warn.Print(err)
		return
	}

	spew.Dump(hashes)
}
```

I get `unexpected EOF`. When I read all bytes and Unmarshall everything is OK.
