### ISSUE TITLE
panic in unsafe.UnsafeString()

### ISSUE THREAD

**Issue by shabbyrobe** [tinylib/msgp#191]
I came across a panic in `UnsafeString` yesterday while fuzzing another part of my app. I found a minimal reproducing test case:

```go
func TestUnsafe(t *testing.T) {
	var b = []byte{0xa0}
	o, _, _ := msgp.ReadStringZC(b)
	if msgp.UnsafeString(o) != "" {
		t.Fail()
	}
}
```

This panics because the length of the string is 0, so the use of `b[0]` in `unsafe.go` fails:

```
--- FAIL: TestUnsafe (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc4200920f0)
	/usr/local/go/src/testing/testing.go:712 +0x2d2
panic(0x1137080, 0x1215f50)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/tinylib/msgp/msgp.UnsafeString(...)
	/Users/bl/code/go/src/github.com/tinylib/msgp/msgp/unsafe.go:27
```

The fix is trivial:

```go
func UnsafeString(b []byte) string {
	l := len(b)
	if l > 0 {
		return *(*string)(unsafe.Pointer(&reflect.StringHeader{Data: uintptr(unsafe.Pointer(&b[0])), Len: l}))
	} else {
		return ""
	}
}
```

It's highly unlikely this would ever be tripped by any generated code as it relies on a key of length 0 somehow making it past `ReadMapKeyPtr`, but it never hurts to remove this kind of potential from exported functions, you can never be sure everyone will heed the ALL CAPS EVIL WARNING!

**Comment by shabbyrobe** [comment]
You can trip it using `msgp.HasKey()` with the map `{"": "test"}`:

```
b := []byte{0x81, 0xa0, 0xa4, 0x74, 0x65, 0x73, 0x74}
msgp.HasKey("foo", b)
// boom!
```

**Comment by shabbyrobe** [comment]
I've also found a reproducible case using just plain 'ol `UnmarshalMsg`. The byte array is just pasted in from the output of the following javascript: `process.stdout.write(msgpack.encode({"": ""}))`

```go
type Test struct { Foo string; Bar string }
b := []byte{0x81, 0xa0, 0xa0}
var t Test
(&t).UnmarshalMsg(b)
// boom!
```
